### PR TITLE
Change MTU to 1280 to circumvent Kabel Deutschland problems

### PR DESCRIPTION
**Pull request by rubo77**
KD and many other providers cut UDP packages at  MTU 1370

### CODE REVIEW

**Comment by ohrensessel** [comment]
this obviously breaks, as another fastd instance is needed on each gateway to support the new mtu. this also means changed port which you did not change.
any reason you are making this pr as a freifunker from kiel? ;)

**Comment by rubo77** [comment]
I amended, This was just as a reminder. I heard of some people, that don't suggest Freifunk any more, due to the unpredictable MTU problems with some providers.

If you want to wait for fastd18 that supports multiple fastd-MTUs, feel free to can close this and I will be quiet ;)

**Comment by ohrensessel** [comment]
If you hear something like that about nodes in hamburg, it doesn't help us
to hear about that at ffnordcon but we need this info right away.

2015-09-12 17:58 GMT+02:00 Ruben Barkow <notifications@github.com>:

**Comment by bdobe** [comment]
We will test mtu 1280 setting in our new experimental versions.

**Pull request closed without merging**
